### PR TITLE
feat: reduce number of dependencies by using lodash isEqual

### PR DESCRIPTION
**Pull request by DRoet**
I could be wrong but I am pretty sure Lodash's isEqual already does a deep check and pretty much does the same thing.

I like small bundle sizes 😄

### CODE REVIEW

**Comment by DRoet** [comment]
Idk why the lockfile updated vue-demi again 😦

**Comment by victorgarciaesgi** [comment]
Ouch you're right I checked bundlephobia and it increased a lot aha

**Comment by victorgarciaesgi** [comment]
It seems to be my fault, the version was not included in the commit but in the npm build

**Comment by victorgarciaesgi** [comment]
I will do it nevermind thanks a lot @DRoet

**Pull request merged**
